"""Todo stuff2

Revision ID: a1a700aebf23
Revises: 38a4753b9523
Create Date: 2020-12-31 00:24:27.184333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1a700aebf23'
down_revision = '38a4753b9523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('done', sa.Boolean(), nullable=True))
    op.drop_column('todo', 'complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complete', sa.BOOLEAN(), nullable=True))
    op.drop_column('todo', 'done')
    # ### end Alembic commands ###
